name: Upstreamed
on:
  push:
    branches:
      - autoformat-test # for testing
#     - main # temporarily disabled

jobs:
  static_analysis:
    name: Static Analysis
    if: false # disabled for testing
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Coverity Scan
        env:
          COVERITY_SCAN_TOKEN: ${{ secrets.COVERITY_TOKEN }}
        run: |
          ./.ci/ci-coverity.sh

  docs:
    name: Publish Documentation
    if: false # disabled for testing
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish
        env:
          DOC_TOKEN: ${{ secrets.DOC_TOKEN }}
        run: |
          ./.ci/ci-docs.sh

  autoformat:
    name: Auto-format code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Format code
        run: |
          ./.ci/ci-autoformat.sh

      - name: Push any formatting changes
        run: |
            git add -u
            $GITHUB_WORKSPACE/.ci/git_push_if_changes.sh
